[project]
name = "paligemma-2-mix"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "keras-hub>=0.21.1",
    "numpy>=2.1.3",
    "pillow>=11.2.1",
    "torch[cuda12]>=2.7.1",
]
